config/routes.rb
ClubcardshuffleCom::Application.routes.draw do

  resources :clubs do |club|
  	resources :cards, only: [:index]
  end
  get 'clubs/:id/shuffle' => 'clubs#shuffle', as: :shuffle
  resources :cards, only: [:new, :create, :show, :edit, :update, :destroy]

  root 'pages#index'

  

end

app/models/card.rb
class Card < ActiveRecord::Base
	include HasBarcode

	belongs_to :club
 	has_barcode :barcode,
 		:outputter => :svg,
 		:type => :code_128,
 		:value => Proc.new { |card| card.number }

	validates_presence_of :club_id, :number
	validates_numericality_of :club_id
	validates_uniqueness_of :number

end

app/models/club.rb
class Club < ActiveRecord::Base

	has_many :cards

	has_attached_file :logo,
 		:styles => {
 			:thumb => '360x360>'
 		},
 		:convert_options => {
 			:original => '-quality 100 -strip',
 			:thumb => '-quality 50 -strip'
 		},
		:storage => :s3,
		:s3_credentials => {
			:access_key_id => 'AKIAJQTVHQUJX223JNPA',
			:secret_access_key => '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'
		},
		:bucket => 'clubcardshuffle',
		:path => ':class/:attachment/:id/:style.:extension',
		:default_url => ActionController::Base.helpers.asset_path('0.png')
	validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

	validates_presence_of :name, :regex
	validates_uniqueness_of :name

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  	respond_to do |format|
  		format.html
  		format.json
  		format.svg { render :inline => @card.barcode_data.html_safe }
  	end
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    respond_to do |format|
	    if @card.number =~ Regexp.new(@card.club.regex)
	      if @card.save
	        format.html { redirect_to @card, notice: 'Card was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @card }
	        format.js { }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @card.errors, status: :unprocessable_entity }
	        format.js { }
	      end
		else
			@card.errors.add(:number, 'Not valid (ex: ' + @card.club.regex)
	    	format.html { render action: 'new' }
			format.json { render json: @card.errors, status: :unprocessable_entity }
	        format.js { }
	    end
	end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:club_id, :number)
    end

	def valid_number?(number)
		unless @card.number =~ Regexp.new(@card.club.regex)
			@card.errors.add(:number, 'The number you provided does not match the pattern (ex: ' + @card.club.regex)
		end
	end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy, :shuffle]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all.order(:name)
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = Club.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(club_params)
    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: 'Club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @club }
      else
        format.html { render action: 'new' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to clubs_url }
      format.json { head :no_content }
    end
  end

  def shuffle
    respond_to do |format|
  		format.json { render json: @club.cards.limit(1).order('RANDOM()') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name, :example, :regex, :logo)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@clubs = Club.all.order(:name).joins(:cards).uniq
  	@card = Card.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>

	<% if @card.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
			<ul>
				<% @card.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :club_id %>
		<%= collection_select(:card, :club_id, Club.all.order(:name), :id, :name, { :prompt => '' }, { :class => 'form-control input-lg' }) %>
	</div>
	<div class="form-group">
		<%= f.label :number %>
		<%= f.text_field :number, :class => 'form-control input-lg' %>
	</div>
	<div class="form-group">
		<%= f.submit 'Save', :class => 'btn btn-primary btn-lg' %>
		<button class="btn btn-text">Cancel</button>
	</div>

<% end %>

app/views/cards/create.js.erb
$('#new').modal('hide');
alert('Thanks for joining the fight!');

app/views/cards/edit.html.erb
<h1>Edit Card</h1>

<div class="row">
	<div class="col-sm-3">
		<%= render 'form' %>
	</div>
</div>

app/views/cards/index.html.erb
<h1>Listing cards</h1>

<table>
  <thead>
    <tr>
      <th>Club</th>
      <th>Number</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.club_id %></td>
        <td><%= card.number %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>Add A Card</h1>

<div class="row">
	<div class="col-sm-3">
		<%= render 'form' %>
	</div>
</div>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Club:</strong>
  <%= @card.club_id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @card.number %>
</p>

<%= @card.barcode_data.html_safe %>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/clubs/_form.html.erb
<%= form_for(@club, :html => {:multipart => true}) do |f| %>

	<% if @club.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>
			<ul>
				<% @club.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, :class => 'form-control input-lg' %>
	</div>
	<div class="form-group">
		<%= f.label :example %>
		<%= f.text_field :example, :class => 'form-control input-lg' %>
	</div>
	<div class="form-group">
		<%= f.label :regex %>
		<%= f.text_field :regex, :class => 'form-control input-lg' %>
	</div>
	<div class="form-group">
		<%= f.label :logo %>
		<%= f.file_field :logo, :class => 'form-control input-lg' %>
	</div>
	<%= f.submit 'Save', :class => 'btn btn-primary btn-lg' %>
	<%= link_to 'Cancel', clubs_path, :class => 'btn btn-link btn-lg' %>

<% end %>

app/views/clubs/edit.html.erb
<h1>Edit Club</h1>

<div class="row">
	<div class="col-sm-4">
		<%= render 'form' %>
	</div>
</div>

app/views/clubs/index.html.erb
<h1>Clubs</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Club</th>
			<th>Example</th>
			<th>Cards</th>
		</tr>
	</thead>
	<tbody>
		<% @clubs.each do |club| %>
			<tr>
				<td>
					<%= image_tag club.logo.url(:thumb), :style => 'margin-right: 5px; width: 18px;' %>
					<%= link_to club.name, edit_club_path(club) %>
				</td>
				<td><%= club.example %></td>
				<td><%= club.cards.count %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to 'New Club', new_club_path, :class => 'btn btn-primary' %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<div class="row">
	<div class="col-sm-4">
		<%= render 'form' %>
	</div>
</div>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<p>
  <strong>Regex:</strong>
  <%= @club.regex %>
</p>

<%= image_tag @club.logo.url(:thumb) %>

<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

app/views/layouts/_ga.html.erb
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-12141881-40', 'clubcardshuffle.com');
	ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Club Card Shuffle - Fight corporate profiling by anonymously sharing club card numbers online.</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= favicon_link_tag "logo.png", rel: "shortcut icon", type: "image/png" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="jumbotron">
			<div class="container">
				<h1>Club Card Shuffle</h1>
				<p class="lead">Fight corporate profiling by anonymously sharing club card numbers online.</p>
				<button class="btn btn-success btn-lg" data-toggle="modal" data-target="#new" style="margin-top: 15px;">Add A Card</button>
			</div>
		</div>
		<div class="container">
			<%= yield %>
		</div>
		<div class="container">
			<footer>
				&copy; <a href="http://www.heyjones.com">Hey Jones!</a>
			</footer>
		</div>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= render 'layouts/ga' %>
	</body>
</html>

app/views/pages/_card.html.erb
<div class="text-center">
	<h3>Can't Find A Card?</h3>
	<p>Send us a photo of the barcode on your Club Card and we'll add it for you!</p>
	<form class="form" role="form">
		<div class="input-file">
			<input type="file" style="display: inline-block; margin-bottom: 15px;"><br>
		</div>
		<button class="btn btn-default">Send</button>
	</form>
</div>

app/views/pages/_new.html.erb
<div id="new" class="modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">

				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

				<%= form_for(@card, remote: true) do |f| %>

					<% if @card.errors.any? %>
						<div id="error_explanation">
							<h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>
							<ul>
								<% @card.errors.full_messages.each do |msg| %>
									<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
					<% end %>
				
					<div class="form-group">
						<%= f.label :club_id %>
						<%= collection_select(:card, :club_id, Club.all.order(:name), :id, :name, { :prompt => '' }, { :class => 'form-control input-lg', :required => true }) %>
					</div>
					<div class="form-group">
						<%= f.label :number %>
						<%= f.text_field :number, :class => 'form-control input-lg', required: true %>
					</div>
					<div class="form-group">
						<%= f.submit 'Save', :class => 'btn btn-primary btn-lg center-block' %>
					</div>
				
				<% end %>

				<%= render 'card' %>

			</div>
		</div>
	</div>
</div>

app/views/pages/_shuffle.html.erb
<div id="shuffle" class="modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">

				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

				<div>
					<img id="shuffle-barcode">
					<p id="shuffle-number"></p>
				</div>

				<button type="button" id="shuffle-bad" class="btn btn-link btn-lg pull-left" data-id="0"><i class="glyphicon glyphicon-thumbs-down"></i></button>
				<button type="button" id="shuffle-good" class="btn btn-link btn-lg pull-right" data-id="0" data-dismiss="modal"><i class="glyphicon glyphicon-thumbs-up"></i></button>

			</div>
		</div>
	</div>
</div>

app/views/pages/index.html.erb
<%= render "shuffle" %>

<%= render "new" %>

<h2>Find A Club Card</h2>

<div class="row">
	<div class="col-sm-4">

		<div style="margin-bottom: 30px; position: relative;">
			<input id="search" type="text" placeholder="ex: Best Buy" class="form-control input-lg">
			<button id="search-clear" class="btn btn-link btn-lg" style="position: absolute; right: 30px; bottom: 0;"><i class="glyphicon glyphicon-remove-circle"></i></button>
			<button id="search-button" class="btn btn-link btn-lg" style="position: absolute; right: 0; bottom: 0;"><i class="glyphicon glyphicon-search"></i></button>
		</div>

	</div>
	<div class="col-sm-8">

		<div id="clubs" class="row">
			<% @clubs.each do |club| %>
				<div data-club="<%= club.name.downcase %>" class="col-sm-4 col-xs-6 club">
					<div class="panel panel-default pick-panel">
						<div class="panel-body">
							<a id="<%= club.id %>" class="pick-club" style="background-image: url('<%= image_url club.logo.url(:thumb) %>');" data-toggle="modal" data-target="#shuffle" data-id="<%= club.id %>" data-name="<%= club.name %>"><%= club.name %></a>
							<span class="badge"><%= club.cards.count.to_i %></span>
						</div>
					</div>
				</div>
			<% end %>
		</div>

	</div>
</div>
<%= render 'card' %>